- name: Install NGINX
  apt: 
    name: nginx
    state: latest

- name: Config NGINX   
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    -  restart nginx

- name: Config Site   
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify:
    -  restart nginx    